

            <div id="pied" class="container-fluid">       
            <p class="text-center">Tous droits réservés Copyright &copy; 2021 </p>
            <div class="d-flex justify-content-between">
            <a href="https://www.facebook.com/" target="blank" class=""><img src="assets/images/facebook.png" alt="facebook" /></a>
            <a href="https://www.instagram.com/?hl=fr" target="blank" class=""><img src="assets/images/instagram.png" alt="instagram" height="50px"/></a>
            <a href="https://twitter.com/" target="blank" class=""><img src="assets/images/twitter.png" alt="twitter" height="55px"/></a>
            </div>        
        </div>
</body>

